In [1]:
#IMPORTING LIBRARIES

import pandas as pd
import numpy as np

In [2]:
#CREATING FILE PATHS

ath_file_path = "athletes.csv"
coaches_file_path = "coaches.csv"
medals_file_path = "medals_total.csv"
medallists_file_path = "medallists.csv"

In [3]:
#IMPORTING ORIGINAL CSV DATA

raw_coaches = pd.read_csv(coaches_file_path)
raw_athlets = pd.read_csv(ath_file_path)
raw_medals = pd.read_csv(medals_file_path)
raw_medallists = pd.read_csv(medallists_file_path)

In [4]:
#viewing raw coaches data

raw_coaches_df = pd.DataFrame(raw_coaches)
raw_coaches.head(10)

,code,name,gender,function,category,country_code,country,country_full,disciplines,events
0,1533246,PEDRERO Ofelia,Female,Coach,C,MEX,Mexico,Mexico,Artistic Swimming,Team
1,1535775,RADHI SHENAISHIL,Male,Head Coach,C,IRQ,Iraq,Iraq,Football,Men
2,1536055,AFLAKIKHAMSEH Majid,Male,Coach,C,IRI,IR Iran,Islamic Republic of Iran,Taekwondo,NaN
3,1536059,YOUSEFY Mehrdad,Male,Coach,C,IRI,IR Iran,Islamic Republic of Iran,Taekwondo,NaN
4,1536060,MADDAH Minoo,Female,Coach,C,IRI,IR Iran,Islamic Republic of Iran,Taekwondo,NaN
5,1536328,LOFTUS Adriana,Female,Coach,C,MEX,Mexico,Mexico,Artistic Swimming,Team
6,1538313,FERRARA Fernando,Male,Head Coach,C,ARG,Argentina,Argentina,Hockey,NaN
7,1538315,GULLA Alejandra,Female,Assistant Coach,C,ARG,Argentina,Argentina,Hockey,Women
8,1538317,CAPURRO Santiago,Male,Assistant Coach,C,ARG,Argentina,Argentina,Hockey,NaN
9,1538745,RONCONI Mariano,Male,Head Coach,C,ARG,Argentina,Argentina,Hockey,NaN

In [5]:
#CREATING A COPY, NEW DATAFRAME AND CSV FOR FURTHER ANALYSIS

raw_coaches_df.copy()

coaches_filter = raw_coaches.drop(columns=['category'])
coach_info_df = pd.DataFrame(coaches_filter)

coach_info_df.to_csv('coach_info.csv', index=False, encoding='utf8')

In [6]:
#RAW DATA VIEWING

raw_athlets_df = pd.DataFrame(raw_athlets)
raw_athlets_df.head(10)

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
5,1532951,ARENAS Lorena,ARENAS L,Lorena ARENAS,Female,Athlete,COL,Colombia,Colombia,Colombia,...,"Father, Jose Otoniel. Mother, Maria Rudy. Has ...",Spanish,Personal: Brent Vallance (AUS),NaN,"Race walker Luis Fernando Lopez (COL), four-ti...",NaN,NaN,NaN,In competition she wears a ring or earrings he...,NaN
6,1533112,McKENZIE Ashley,McKENZIE A,Ashley McKENZIE,Male,Athlete,JAM,Jamaica,Jamaica,Jamaica,...,"One daughter, Lana-Rose, who lives in France",English,Personal and National: Luke Preston (GBR),"""I was thrown over [an argument about] a Pokem...","Boxer Muhammad Ali, born Cassius Clay (USA), f...","""My coach Luke Preston. We've been a team for ...",NaN,NaN,NaN,NaN
7,1533136,BASS BITTAYE Gina Mariam,BASS BITTAYE GM,Gina Mariam BASS BITTAYE,Female,Athlete,GAM,Gambia,Gambia,Gambia,...,"Husband, Mustapha Bittaye - physical education...","English, French",Personal: Christophe Belliard (FRA),“I started running when I was in primary schoo...,"Sprinter Shelly-Ann Fraser-Pryce (JAM), three ...",NaN,"""If you believe in yourself, never be discoura...",NaN,NaN,NaN
8,1533176,CAMARA Ebrahima,CAMARA E,Ebrahima CAMARA,Male,Athlete,GAM,Gambia,Gambia,Gambia,...,Married. One daughter. Has three brothers,"Arabic, English, French, Mandinka, Wolof",Personal: Christophe Belliard (FRA),"""I love running and I was fast a child."" (Athl...","Sprinter Gina Mariam Bass Bittaye (GAM), two-t...","Momodou Lamin Kujabi, a former international a...","""What does not kill you makes you stronger."" (...",NaN,NaN,NaN
9,1533188,RUEDA SANTOS Lizeth,RUEDA SANTOS L,Lizeth RUEDA SANTOS,Female,Athlete,MEX,Mexico,Mexico,Mexico,...,NaN,Spanish,Personal: Eugenio Chimal (MEX),Was a competitive swimmer from age 12 and went...,NaN,NaN,NaN,NaN,NaN,Competed in marathon swimming at London 2012. ...

In [7]:
#CREATING A COPY, NEW DATAFRAME AND CSV FOR FURTHER ANALYSIS 

raw_athlets_df.copy()
athletes_filter = raw_athlets_df[["code", "name", "name_tv", "country_code", "country", "country_full", "height", "weight", "disciplines", "events","birth_date", "coach"]]
athletes_df = pd.DataFrame(athletes_filter)
athletes_df.head(10)

athletes_df.to_csv('athletes_data.csv', index=False, encoding='utf8')

In [8]:
#RAW DATA VIEW AND SAVING TO CSV

raw_medals_df = pd.DataFrame(raw_medals)
raw_medals_df.head(10)

raw_medals_df.to_csv('medal_count.csv', index=False, encoding='utf8')

In [9]:
#VIEWING RAW DATA

raw_medallists_df = pd.DataFrame(raw_medallists)
raw_medallists_df.head(10)

,medal_date,medal_type,medal_code,name,gender,country,country_code,nationality,team,team_gender,discipline,event,event_type,url_event,birth_date,code
0,2024-07-27,Gold Medal,1,EVENEPOEL Remco,Male,Belgium,BEL,Belgium,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,2000-01-25,1903136
1,2024-07-27,Silver Medal,2,GANNA Filippo,Male,Italy,ITA,Italy,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1996-07-25,1923520
2,2024-07-27,Bronze Medal,3,van AERT Wout,Male,Belgium,BEL,Belgium,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1994-09-15,1903147
3,2024-07-27,Gold Medal,1,BROWN Grace,Female,Australia,AUS,Australia,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1992-07-07,1940173
4,2024-07-27,Silver Medal,2,HENDERSON Anna,Female,Great Britain,GBR,Great Britain,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1998-11-14,1912525
5,2024-07-27,Bronze Medal,3,DYGERT Chloe,Female,United States,USA,United States,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1997-01-01,1955079
6,2024-07-27,Gold Medal,1,OH Sanguk,Male,Korea,KOR,Korea,NaN,NaN,Fencing,Men's Sabre Individual,HATH,/en/paris-2024/results/fencing/men-s-sabre-ind...,1996-09-30,1927149
7,2024-07-27,Silver Medal,2,FERJANI Fares,Male,Tunisia,TUN,Tunisia,NaN,NaN,Fencing,Men's Sabre Individual,HATH,/en/paris-2024/results/fencing/men-s-sabre-ind...,1997-07-22,1937783
8,2024-07-27,Bronze Medal,3,SAMELE Luigi,Male,Italy,ITA,Italy,NaN,NaN,Fencing,Men's Sabre Individual,HATH,/en/paris-2024/results/fencing/men-s-sabre-ind...,1987-07-25,1924595
9,2024-07-27,Gold Medal,1,KONG Man Wai Vivian,Female,"Hong Kong, China",HKG,"Hong Kong, China",NaN,NaN,Fencing,Women's Épée Individual,HATH,/en/paris-2024/results/fencing/women-s-epee-in...,1994-02-08,1963262

In [10]:
#CREATING A COPY, NEW DATAFRAME AND CSV FOR FURTHER ANALYSIS 

medallists = raw_medallists.copy()
medallists_filter = medallists[["medal_type", "medal_code", "name", "country", "country_code", "nationality", "discipline", "event", "birth_date", "code"]]
medallists_df = pd.DataFrame(medallists_filter)
medallists_df.head(10)

medallists_df.to_csv('medallist_info.csv', index=False, encoding='utf8')